### PR TITLE
manually count entries in partial data table

### LINKED ISSUE #2: Data from YAML frontmatter is broken
The README currently shows the issue where data from the YAML frontmatter isn't being interpolated as expected. The examples below should read "Hello, friend!" and "Hello, amigo!" respectively.

image

### PR DESCRIPTION
**Pull request by zkamvar**
I believe this will fix #2. I don't know why, but it seems that having a table with named elements means that you can't use the `#` syntax to get the length (only for numeric indexes)

### CODE REVIEW

File: _extensions/partials/quarto-partials.lua [hunk 1]
```diff
@@ -127,7 +127,11 @@ local function quarto_partial(args, kwargs, meta, raw_args, context)
     partial_data = copy(meta[partial_key])
   end
 
-  if #partial_data > 0 then
+  local nkeys = 0
+  for _ in pairs(partial_data) do
+    nkeys = nkeys + 1
+  end
+  if nkeys > 0 then
```
Comment (gadenbuie) [inline _extensions/partials/quarto-partials.lua]:
```suggestion
  if next(partial_data) then
```

**Review by gadenbuie — COMMENTED** [review]
Thanks! You're spot on about the problem (and I wonder why I thought that worked at the time??)...

I did a little research and I think we can use `next(partial_data)` instead of `#partial_data > 0`, since `next()` returns `nil` if there aren't any fields in a table.

```lua
local t1 = {1, 2, 3}  -- A sequence
print(#t1)
--> 3

local t2 = {a = 1, b = 2, c = 3}  -- A table with named elements
print(#t2)
--> 0

local function tableLength(t)
    local count = 0
    for _ in pairs(t) do
        count = count + 1
    end
    return count
end

if tableLength(t1) > 0 then
    print("t1 has more than 0 items")
end
--> t1 has more than 0 items

if tableLength(t2) > 0 then
    print("t2 has more than 0 items")
end
--> t2 has more than 0 items

if next(t1) then
    print("t1 has at least one item")
end
--> t1 has at least one item

if next(t2) then
    print("t2 has at least one item")
end
--> t2 has at least one item
```

(You can [run that in the browser here](https://glot.io/snippets/h5lqz6hdbu).)

**Comment by zkamvar** [comment]
Thank you for being quick on the draw about this!

**Review by gadenbuie — APPROVED** [review]
Thanks again for the fix!
